### ISSUE TITLE
Followed instructions but plugin failed to load

### ISSUE THREAD

**Issue by travismcgrath** [0xC0000054/pdn-gmic#1]
I followed the directions in the readMe but got this error.

"System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.ComponentModel.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"

**Comment by 0xC0000054** [comment]
That error message appears to indicate that you are running an outdated version of Paint.NET.
The plugin requires Paint.NET 4.3.10 or later.

**Comment by travismcgrath** [comment]
Sure enough! I was on 4.2.5. Will udpate and try it now. Thank you.
